name: Build_CI_Vue_Dev

on:
  pull_request:
    branches:
      - develop

concurrency: develop_CI

jobs:
  build-ci:
    name: "Build and CI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cypress CI Run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build:development
          start: npm run serve
          wait-on: "http://localhost:4200"
          config-file: cypress.config.ci.js

  automerge:
    needs: build-ci
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.11.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
